name: VNStock Daily Collector

on:
  schedule:
    # 17:00 VN = 10:00 UTC
    - cron: '0 10 * * 1-5'

  workflow_dispatch:

jobs:
  collect-vn:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        env:
          VNSTOCK_API_KEY: ${{ secrets.VNSTOCK_API_KEY }}
        run: |
          python -m pip install --upgrade pip
          
          # 1. Tải file cấu hình các thư viện phụ thuộc từ server Vnstock
          pip install -r https://vnstocks.com
          
          # 2. Chạy lệnh cài đặt bản nâng cao thông qua môi trường bảo mật
          pip install --extra-index-url https://vnstocks.com vnstock_data pandas supabase


      - name: Run VNStock collector
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
        run: python scripts/collect-vnstock.py